version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in prebuild
  build:
    commands:
      - echo Build started on `date`
      - echo "Building without integration tests or Docker"
      - mvn -B clean package \
        -DskipTests \
        -Dspring.docker.compose.enabled=false \
        -Dspring.docker.compose.skip.in-tests=true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-petclinic-4.0.0.BUILD-SNAPSHOT.jar
