version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in prebuild
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipITs
      # - mvn package -Dspring.docker.compose.skip.in-tests=true #Same as above
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar